### ISSUE TITLE
newlines break the input system

### ISSUE THREAD

**Issue by svmorris** [bczsalba/teahaz-client#1]
newlines seem to be blocked somehow when typing, but you can paste them in which causes many visual bugs

[video](https://user-images.githubusercontent.com/46561460/106281991-46c9ee80-6240-11eb-9e44-477c80ba4119.mp4)

**Comment by bczsalba** [comment]
This will be fixed as more of the multiline system is implemented, though I may add a temporary fix until then.

**Comment by bczsalba** [comment]
fixed :rocket:
