### ISSUE TITLE
keep cursor option doesn't reprint the right border of the settings menu when changed

### ISSUE THREAD

**Issue by svmorris** [bczsalba/teahaz-client#2]
when you change the keep_cursor... option in the settings menu with <space>, it probably doesn't reprint the right bar. This leads to a double border.
![screenshot working](https://user-images.githubusercontent.com/46561460/106283406-2e5ad380-6242-11eb-82fb-b32e0b9498c9.png)
![Screenshot broken](https://user-images.githubusercontent.com/46561460/106283414-30249700-6242-11eb-9179-0645aac8ebc9.png)

**Comment by bczsalba** [comment]
Can you paste the contents of `teahaz/client/log`?

**Comment by svmorris** [comment]
sure 
```
starting teahaz at size 213 61
<function return_to_infield at 0x7f0fd3455310> {'_': '"'}
```

**Comment by bczsalba** [comment]
fixed :rocket:
