### ISSUE TITLE
can we not spam get when user is not logged in

### ISSUE THREAD

**Issue by svmorris** [bczsalba/teahaz-client#3]

**Comment by svmorris** [comment]
fuck i accidentally submitted.
but the point is that get is spammed when the user is not yet logged in

this fills up my admin panel with red and i get worried. pls at some point could you make this not happen :pray:

**Comment by bczsalba** [comment]
does the server provide any way to check if a user is logged in? 

also again literally all of the current messaging is a prototype, it's not gonna be this trash lmao

**Comment by svmorris** [comment]
for now just doing `get messages` is an option but i understand that that suck

how about if i add a get method to /login that will respond with `"OK", 200` if logged in and `"client not logged in", 401` if not?

**Comment by bczsalba** [comment]
i mean it could work, sure

**Comment by svmorris** [comment]
cool, ill do that

**Comment by svmorris** [comment]
its done and its up on the server
doing a get request to /login with the username in http header will return you whether or not you are logged in

code example:
```py

def check_login(s, username):
    url = url + "/login"

    a = {
        "username": username,
    }

    res = s.get(url=url, headers=a)

    return res.text
```

**Comment by bczsalba** [comment]
:rocket: fixed

(has been for a while lol)
