### ISSUE TITLE
Hii~~

### ISSUE THREAD

**Issue by KawaiiCoder69** [bczsalba/teahaz-client#4]
I fixie wixied the JSON-apu fucksy wucksie!!! _xpp_

You should repwace the Prototypes.func wiff a more ~streamylined~~ kawaii **Pwototypiee.Funkywunks** object that make the Python go sooper dooper fast!!
xD _*starts twerking*_

Pwease fix me senpai!! _UwU_

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
fella

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
I closed it because i dont understand what it says
