### ISSUE TITLE
Adding reactions :)

### ISSUE THREAD

**Issue by svmorris** [bczsalba/teahaz-client#5]
I want to let you know that the server has had reaction support for over a week now! :slightly_smiling_face: 

## implementation:

When sending messages the server now has support for a `replyId` field. This field is optional, and the default value is Null. When sending a messages you can set this field to any valid UUID, but I recommend setting it to the id  of another message.

### upcoming features to support this function:
I in the future I will add support for getting a message by Id, which would allow users to see replies for messages that happened long enough that It was not loaded. **NOTE:** due to upcoming encryption this still wont allow new users to see previous messages

Im in a rush so I hope I made this clear :slightly_smiling_face:

**Comment by bczsalba** [comment]
I think you meant reply support, reactions are a bit different and shouldn't be using the same field. 

I'll finish basic messaging functions like file send/view, and after that I'll work on adding this (and by then hopefully edit/delete too! 😺)

**Comment by svmorris** [comment]
yup. sorry, that's what I meant

and nice close there :slightly_smiling_face:

**Comment by bczsalba** [comment]
implemented :rocket:

now just waiting on you and filetype & reaction support 😸
